FROM node:18-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm install

# Копируем весь код
COPY . .

# Генерируем Prisma клиент
RUN npx prisma generate

# Открываем порт
EXPOSE 5000

# Запускаем сервер
CMD ["npm", "run", "start"]